{% set name = "ddtrace" %}
{% set version = "2.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: f185c6dd88cd04884f0ad27b37f14d837274e8fc4dc43407781334d92d41c3bc

build:
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - ninja
    - make
  host:
    - cython
    - python
    - pip
    - setuptools-scm >=4
    - setuptools-rust <2
  run:
    - python
    - bytecode >=0.16.0
    - envier >=0.5,<1
    - legacy-cgi >=2.0.0  # [py>=313]
    - opentelemetry-api >=1
    - protobuf >=3
    - typing_extensions
    - xmltodict >=0.12
    - wrapt >=1

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - pip
  commands:
    - pip check
    - ddtrace-run --help

about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: 0BSD AND Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE.BSD3
    - LICENSE.Apache
    - NOTICE

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
    - dbast
